### Create a new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVvQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3Njc3NzM1NTJ9.pXYE5b9RQEYzqWpGZBjkSzkfKU7FBOac_6flzWjq208

{
  "author": "code master",
  "title": "React/Redux",
  "url": "https://react.com/Redux",
  "likes": 10
}